version: '3'
services:

  apps:
    image: zsoltvarju/qras:open-semantic-search
    depends_on:
      - rabbitmq
      - solr
      - tika
    volumes:
      - config_etl:/etc/opensemanticsearch
      - config_solr-php-ui:/etc/solr-php-ui
      - data_db:/var/opensemanticsearch/db
      - data_media:/var/opensemanticsearch/media
    environment:
      - SOLR_PHP_UI_SOLR_HOST=solr
      - OPEN_SEMANTIC_ETL_MQ_BROKER=amqp://rabbitmq
      - OPEN_SEMANTIC_ETL_SOLR=http://solr:8983/solr/
      - OPEN_SEMANTIC_ETL_TIKA_SERVER=http://tika:9998
      - OPEN_SEMANTIC_ETL_TIKA_SERVER_FAKECACHE=http://tika-fakecache:9998
      - OPEN_SEMANTIC_ETL_SPACY_SERVER=http://spacy-services:8080
      - OPEN_SEMANTIC_ETL_NEO4J_HOST=neo4j
      - FLOWER_URL=http://flower:5555/flower
    env_file:
      - neo4j.env
    ports:
      - "8080:80"

  etl:
    image: zsoltvarju/qras:open-semantic-etl
    depends_on:
      - apps
      - rabbitmq
      - solr
      - tika
      - tika-fakecache
      - spacy-services
    environment:
      - OPEN_SEMANTIC_ETL_MQ_BROKER=amqp://rabbitmq
      - OPEN_SEMANTIC_ETL_METADATA_SERVER=http://apps/search-apps/annotate/json
      - OPEN_SEMANTIC_ETL_SOLR=http://solr:8983/solr/
      - OPEN_SEMANTIC_ETL_TIKA_SERVER=http://tika:9998
      - OPEN_SEMANTIC_ETL_TIKA_SERVER_FAKECACHE=http://tika-fakecache:9998
      - OPEN_SEMANTIC_ETL_SPACY_SERVER=http://spacy-services:8080
      - OPEN_SEMANTIC_ETL_NEO4J_HOST=neo4j
      - OMP_THREAD_LIMIT=1
    env_file:
      - neo4j.env
    volumes:
      - config_etl:/etc/opensemanticsearch:ro
      - data_media:/var/opensemanticsearch/media
      - cache_tesseract:/var/cache/tesseract

  solr:
    image: zsoltvarju/qras:solr-7.7.2
    environment:
      - SOLR_LOCAL_HOST=0.0.0.0
    volumes:
      - data_solr:/opt/solr/server/solr
    ports:
      - "8983:8983"

  tika:
    image: zsoltvarju/qras:tika-server
    environment:
      - OMP_THREAD_LIMIT=1
      - TIKA_CONFIG=/etc/tika/tika-config-cache.xml
    volumes:
      - cache_tesseract:/var/cache/tesseract

  tika-fakecache:
    image: zsoltvarju/qras:tika-server
    environment:
      - OMP_THREAD_LIMIT=1
      - TIKA_CONFIG=/etc/tika/tika-config-fakecache.xml
    volumes:
      - cache_tesseract:/var/cache/tesseract

  spacy-services:
    image: zsoltvarju/qras:spacy-services

  rabbitmq:
    image: zsoltvarju/qras:rabbitmq

  flower:
    image: zsoltvarju/qras:flower
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - FLOWER_PORT=5555
      - FLOWER_URL_PREFIX=flower
    depends_on:
      - rabbitmq

  neo4j:
    image: zsoltvarju/qras:neo4j
    restart: always
    env_file:
      - neo4j.env
    volumes:
      - data_neo4j:/data

  cron:
    image: zsoltvarju/qras:cron

volumes:
  config_etl:
  config_solr-php-ui:
  data_db:
  data_media:
  data_neo4j:
  data_solr:
  cache_tesseract:
